modLoader="javafml"
loaderVersion="[43,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/MattCzyr/ConsoleFilter/issues"

[[mods]]
modId="consolefilter"
version="${file.jarVersion}"
displayName="ConsoleFilter"
authors="NgLoader, MarkKoz, ChaosTheDude"
description="Hide annoying messages from your console logs."
displayTest="IGNORE_ALL_VERSION"