modLoader="javafml"
loaderVersion="[36,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/MattCzyr/ConsoleFilter/issues"

[[mods]]
modId="consolefilter"
version="1.16.5"
displayName="ConsoleFilter"
authors="NgLoader, MarkKoz, ChaosTheDude, DerHammerclock"
description="Hide annoying messages from your console logs."
