issueTrackerURL="https://github.com/MattCzyr/ConsoleFilter/issues"
license="CC BY-NC-SA 4.0"

[[mods]]
    modId="consolefilter"
    version="${mod_version}"
    displayName="Console Filter"
    displayURL="https://github.com/MattCzyr/ConsoleFilter"
    authors="ChaosTheDude"
    description='''
    Hide messages from your console logs.
    '''
    displayTest="IGNORE_ALL_VERSION"

[[dependencies.consolefilter]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.consolefilter]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"